### PR TITLE
eightball command

### PR DESCRIPTION
**Pull request by PHLAK**
Impliments the `/bot eightball [question]` command.  Returns a Magic 8-ball yes or no answer.

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/31/

**Build Log**
_last 25 lines_

```
[...truncated 5 lines...]
 > git config remote.origin.url https://github.com/TheInnerCircleO/hangupsbot # timeout=10
Fetching upstream changes from https://github.com/TheInnerCircleO/hangupsbot
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/TheInnerCircleO/hangupsbot +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/19/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/19/merge^{commit} # timeout=10
Checking out Revision 74c0e5761cff07a952bbf24b7268b2a7b598b619 (refs/remotes/origin/pr/19/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 74c0e5761cff07a952bbf24b7268b2a7b598b619
First time build. Skipping changelog.
[workspace] $ /bin/bash /tmp/hudson5260337607730938101.sh
pep8 recreate: /var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8
pep8 installdeps: -r/var/lib/jenkins/jobs/hangups_tox/workspace/requirements.txt, -r/var/lib/jenkins/jobs/hangups_tox/workspace/test-requirements.txt
pep8 develop-inst: /var/lib/jenkins/jobs/hangups_tox/workspace
pep8 runtests: PYTHONHASHSEED='1412197223'
pep8 runtests: commands[0] | flake8
./hangupsbot/commands.py:394:80: E501 line too long (84 > 79 characters)
                bot.send_message(event.conv, 'Invalid argument: {}'.format(args[0]))
                                                                               ^
ERROR: InvocationError: '/var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8/bin/flake8'
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
Build step 'Execute shell' marked build as failure
Setting status of 723cf7108705a5dc1a4e2fd196f03857750215e4 to FAILURE with url http://bock.systems:8080/job/hangups_tox/31/ and message: Merged build finished.
```

Oh No...

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/32/

**Build Log**
_last 25 lines_

```
[...truncated 5 lines...]
 > git config remote.origin.url https://github.com/TheInnerCircleO/hangupsbot # timeout=10
Fetching upstream changes from https://github.com/TheInnerCircleO/hangupsbot
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/TheInnerCircleO/hangupsbot +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/19/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/19/merge^{commit} # timeout=10
Checking out Revision 2d9f7f9c398c829407a4dc3348d2631e941fd0f1 (refs/remotes/origin/pr/19/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 2d9f7f9c398c829407a4dc3348d2631e941fd0f1
First time build. Skipping changelog.
[workspace] $ /bin/bash /tmp/hudson939852911053471549.sh
pep8 recreate: /var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8
pep8 installdeps: -r/var/lib/jenkins/jobs/hangups_tox/workspace/requirements.txt, -r/var/lib/jenkins/jobs/hangups_tox/workspace/test-requirements.txt
pep8 develop-inst: /var/lib/jenkins/jobs/hangups_tox/workspace
pep8 runtests: PYTHONHASHSEED='731575472'
pep8 runtests: commands[0] | flake8
./hangupsbot/commands.py:394:80: E501 line too long (84 > 79 characters)
                bot.send_message(event.conv, 'Invalid argument: {}'.format(args[0]))
                                                                               ^
ERROR: InvocationError: '/var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8/bin/flake8'
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
Build step 'Execute shell' marked build as failure
Setting status of bf41b4ec315959adabf31a42ec42a095df13896c to FAILURE with url http://bock.systems:8080/job/hangups_tox/32/ and message: Merged build finished.
```

Oh No...

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/33/
Tests Passed, Yay.

**Comment by uberscientist** [comment]
shuffle and choice seem redundant, but it sure feels good to some level of consciousness within my being :+1: :8ball:

**Pull request merged**
