### PR TITLE
/bot prs

### PR DESCRIPTION
**Pull request by PHLAK**
Impliments 'prs' command for listing open PRs against the TheInnerCircleO/hangupsbot project on GitHub

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/13/

**Build Log**
_last 25 lines_

```
[...truncated 23 lines...]
^
./hangupsbot/commands.py:524:80: E501 line too long (83 > 79 characters)
    prs = get_json('https://api.github.com/repos/TheInnerCircleO/hangupsbot/pulls')
                                                                               ^
./hangupsbot/commands.py:535:80: E501 line too long (89 > 79 characters)
        segments.append(hangups.ChatMessageSegment('\n', hangups.SegmentType.LINE_BREAK))
                                                                               ^
./hangupsbot/commands.py:536:80: E501 line too long (89 > 79 characters)
        segments.append(hangups.ChatMessageSegment('\n', hangups.SegmentType.LINE_BREAK))
                                                                               ^
./hangupsbot/commands.py:537:80: E501 line too long (81 > 79 characters)
        segments.append(hangups.ChatMessageSegment('[{}] '.format(pr['number'])))
                                                                               ^
./hangupsbot/commands.py:538:80: E501 line too long (118 > 79 characters)
        segments.append(hangups.ChatMessageSegment(pr['title'], hangups.SegmentType.LINK, link_target=pr['html_url']))
                                                                               ^
./hangupsbot/commands.py:540:80: E501 line too long (129 > 79 characters)
        segments.append(hangups.ChatMessageSegment(pr['user']['login'], hangups.SegmentType.LINK, link_target=pr['user']['url']))
                                                                               ^
ERROR: InvocationError: '/var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8/bin/flake8'
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
Build step 'Execute shell' marked build as failure
Setting status of 2d147ef8fbebd6f703468b07238ffda2ae546c8a to FAILURE with url http://bock.systems:8080/job/hangups_tox/13/ and message: Merged build finished.
```

Oh No...

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/14/
Tests Passed, Yay.

**Comment by DavidCaudill** [comment]
looks good to me, +1

**Comment by uberscientist** [comment]
Looks exciting, might want to try and put that double append on lines 538 and 542 into one append, but let's move fast and break things +1

**Comment by DavidCaudill** [comment]
chris k, merge when ready.

**Pull request merged**
