### PR TITLE
roll command

### PR DESCRIPTION
**Pull request by PHLAK**
Implemented basic dice rolling command

**Usage:**

```
/bot roll 1d6 4d20 2d50
```

### CODE REVIEW

**Comment by DavidCaudill** [comment]
I'm not too sure on the error handling of the bot, I think it would be catch it itself, but how would /bot roll asdf 2432 ffffff be handled?

**Comment by PHLAK** [comment]
I had considered this too.  Will likely add a regex to validate argument syntax in the future.

**Comment by DavidCaudill** [comment]
I'm more concerned about it crashing the bot then handling a bad command gracefully, will the bot still be running if i send that?

**Comment by PHLAK** [comment]
The bot continued running when sending bad arguments, it just didn't complete the command.

**Comment by Penguin2600** [comment]
I swear to god I will pistol whip the next person who works on this during working hours.

**Comment by DavidCaudill** [comment]
we need a pistol whip command for the bot

**Comment by PHLAK** [comment]
you-mean-shenanigans-o

**Pull request merged**
