### PR TITLE
stock ticker price command

### PR DESCRIPTION
**Pull request by DavidCaudill**
Original author: Christopher Toledo.

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox/6/

**Build Log**
_last 25 lines_

```
GitHub pull request #9 of commit c833a87baae9438991de53192c6807684f0e8783 automatically merged.
Setting status of c833a87baae9438991de53192c6807684f0e8783 to PENDING with url http://bock.systems:8080/job/Run%20Tox/6/ and message: Merged build started.
Building in workspace /var/lib/jenkins/jobs/Run Tox/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/TheInnerCircleO/hangupsbot # timeout=10
Fetching upstream changes from https://github.com/TheInnerCircleO/hangupsbot
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/TheInnerCircleO/hangupsbot +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/9/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/9/merge^{commit} # timeout=10
Checking out Revision ea6574aeaeaeff8209f66712afc771b6fdd3389f (refs/remotes/origin/pr/9/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ea6574aeaeaeff8209f66712afc771b6fdd3389f
First time build. Skipping changelog.
[workspace] $ /bin/bash /tmp/hudson1962863790351971708.sh
/tmp/hudson1962863790351971708.sh: line 2: tox: command not found
Build step 'Execute shell' marked build as failure
Setting status of c833a87baae9438991de53192c6807684f0e8783 to FAILURE with url http://bock.systems:8080/job/Run%20Tox/6/ and message: Merged build finished.
```

Oh No....

**Comment by Penguin2600** [comment]
fluttershy, test this please

**Comment by DavidCaudill** [comment]
not my fault you dont know tox

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox/7/

**Build Log**
_last 25 lines_

```
GitHub pull request #9 of commit c833a87baae9438991de53192c6807684f0e8783 automatically merged.
Setting status of c833a87baae9438991de53192c6807684f0e8783 to PENDING with url http://bock.systems:8080/job/Run%20Tox/7/ and message: Merged build started.
Building in workspace /var/lib/jenkins/jobs/Run Tox/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/TheInnerCircleO/hangupsbot # timeout=10
Fetching upstream changes from https://github.com/TheInnerCircleO/hangupsbot
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/TheInnerCircleO/hangupsbot +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/9/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/9/merge^{commit} # timeout=10
Checking out Revision 718a9aafda41e22efa741ce62c90eb2c377e9ef1 (refs/remotes/origin/pr/9/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 718a9aafda41e22efa741ce62c90eb2c377e9ef1
First time build. Skipping changelog.
[workspace] $ /bin/bash /tmp/hudson2552910835177754671.sh
/tmp/hudson2552910835177754671.sh: line 2: tox: command not found
Build step 'Execute shell' marked build as failure
Setting status of c833a87baae9438991de53192c6807684f0e8783 to FAILURE with url http://bock.systems:8080/job/Run%20Tox/7/ and message: Merged build finished.
```

Test FAILed.

**Comment by Penguin2600** [comment]
fluttershy, test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/8/

**Build Log**
_last 25 lines_

```
[...truncated 21 lines...]
    retcode = Session(config).runcommand()
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 339, in runcommand
    return self.subcommand_test()
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 477, in subcommand_test
    if self.setupenv(venv):
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 396, in setupenv
    status = venv.update(action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 134, in update
    self.create(action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 200, in create
    self._pcall(args, venv=False, action=action, cwd=basepath)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 383, in _pcall
    return action.popen(args, cwd=cwd, env=env, redirect=redirect, ignore_ret=ignore_ret)
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 85, in popen
    fout = self._initlogpath(self.id)
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 77, in _initlogpath
    f = path.open('w')
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 343, in open
    return py.error.checked_call(open, self.strpath, mode)
  File "/usr/local/lib/python2.7/dist-packages/py/_error.py", line 84, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EACCES: [Permission denied]: open('/var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8/log/pep8-2.log', 'w')
Build step 'Execute shell' marked build as failure
Setting status of c833a87baae9438991de53192c6807684f0e8783 to FAILURE with url http://bock.systems:8080/job/hangups_tox/8/ and message: Merged build finished.
```

Oh No...

**Comment by DavidCaudill** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/10/

**Build Log**
_last 25 lines_

```
[...truncated 21 lines...]
    retcode = Session(config).runcommand()
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 339, in runcommand
    return self.subcommand_test()
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 477, in subcommand_test
    if self.setupenv(venv):
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 396, in setupenv
    status = venv.update(action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 134, in update
    self.create(action)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 200, in create
    self._pcall(args, venv=False, action=action, cwd=basepath)
  File "/usr/local/lib/python2.7/dist-packages/tox/_venv.py", line 383, in _pcall
    return action.popen(args, cwd=cwd, env=env, redirect=redirect, ignore_ret=ignore_ret)
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 85, in popen
    fout = self._initlogpath(self.id)
  File "/usr/local/lib/python2.7/dist-packages/tox/_cmdline.py", line 77, in _initlogpath
    f = path.open('w')
  File "/usr/local/lib/python2.7/dist-packages/py/_path/local.py", line 343, in open
    return py.error.checked_call(open, self.strpath, mode)
  File "/usr/local/lib/python2.7/dist-packages/py/_error.py", line 84, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EACCES: [Permission denied]: open('/var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8/log/pep8-3.log', 'w')
Build step 'Execute shell' marked build as failure
Setting status of 77a15dbed2726f10cf9e41569648867c6d9330db to FAILURE with url http://bock.systems:8080/job/hangups_tox/10/ and message: Merged build finished.
```

Oh No...

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/11/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/12/
Tests Passed, Yay.

**Comment by PHLAK** [comment]
:+1:

**Pull request merged**
