### PR TITLE
Revert "Improved thoughs"

### PR DESCRIPTION
**Pull request by uberscientist**
Reverts TheInnerCircleO/hangupsbot#13

Let's try this again, maybe a little less DGAF on pulling changes this time around though

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/19/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
0z7pboo

**Comment by uberscientist** [comment]
zfb9zhu

**Comment by PHLAK** [comment]
Why did we revert this instead of fixing whatever is wrong?

**Comment by PHLAK** [comment]
Oh, you closed it.

**Comment by uberscientist** [comment]
nerpnerp

**Pull request closed without merging**
