### PR TITLE
Refactored 'roll' command to utilize segments

### PR DESCRIPTION
**Pull request by PHLAK**
Refactored 'roll' command to utilize segments.  This preserves oder.

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/16/
Tests Passed, Yay.

**Comment by uberscientist** [comment]
maybe it will be prettier +1

**Comment by DavidCaudill** [comment]
looks good to me, +1. should look more into for loops, shouldnt need to use a counter var.

**Comment by PHLAK** [comment]
@Eamnon Look again, I replaced the while loop with a for loop.

**Pull request merged**
