### PR TITLE
Improved thoughs

### PR DESCRIPTION
**Pull request by PHLAK**
Improved 'thoughts' command by linking title to the corresponding Reddit topic.

**Note:** Renamed `get_topic` function to `get_random_topic` and made it return the topic JSON object instead of just the title text.

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/17/
Tests Passed, Yay.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/18/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
"improved"

**Comment by uberscientist** [comment]
I heard rumors of DGAF, GO FORTH +!

**Comment by uberscientist** [comment]
tfw merging

**Pull request merged**
