### PR TITLE
stock ticker price command

### PR DESCRIPTION
**Pull request by uberscientist**
Ok I think this is how it's done? (jam it in)

### CODE REVIEW

**Comment by System-Flenser** [comment]
Um, I could test this, if thats ok with an admin...

**Comment by Penguin2600** [comment]
this is ok to test fluttershy.

**Comment by uberscientist** [comment]
Hello fluttershy, can you maybe let me check out your treehouse sometime...😊

**Comment by Penguin2600** [comment]
fluttershy add to whitelist

**Comment by DavidCaudill** [comment]
new line that is a commented out line of code?
same line commit messages are going to eat up your line limit once linting is enabled.
might want to also drop ln 353 down to shorten it.

**Comment by Penguin2600** [comment]
add to whitelist fluttershy

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox/2/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
test this please

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/Run%20Tox/3/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
Needs to be rebased after tox added -1

**Pull request closed without merging**
