### PR TITLE
dilbert command improvements

### PR DESCRIPTION
**Pull request by PHLAK**
This is a work in progress, looking for feedback.  Current improvements:
- Can now link specific comics by date `/bot dilbert YYYY-MM-DD`
- All links use the cannonical permalink: http://dilbert.com/strip/YYYY-MM-DD
- Running `/bot dilbert` without arguments links to the current days cannonical permalink
- Impliments segments

### CODE REVIEW

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/27/

**Build Log**
_last 25 lines_

```
[...truncated 5 lines...]
 > git config remote.origin.url https://github.com/TheInnerCircleO/hangupsbot # timeout=10
Fetching upstream changes from https://github.com/TheInnerCircleO/hangupsbot
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/TheInnerCircleO/hangupsbot +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/17/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/17/merge^{commit} # timeout=10
Checking out Revision ff19137b039e2bb2a07faeee548a4fb8f57e2242 (refs/remotes/origin/pr/17/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ff19137b039e2bb2a07faeee548a4fb8f57e2242
First time build. Skipping changelog.
[workspace] $ /bin/bash /tmp/hudson6099625966166227709.sh
pep8 recreate: /var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8
pep8 installdeps: -r/var/lib/jenkins/jobs/hangups_tox/workspace/requirements.txt, -r/var/lib/jenkins/jobs/hangups_tox/workspace/test-requirements.txt
pep8 develop-inst: /var/lib/jenkins/jobs/hangups_tox/workspace
pep8 runtests: PYTHONHASHSEED='1889157099'
pep8 runtests: commands[0] | flake8
./hangupsbot/commands.py:394:80: E501 line too long (84 > 79 characters)
                bot.send_message(event.conv, 'Invalid argument: {}'.format(args[0]))
                                                                               ^
ERROR: InvocationError: '/var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8/bin/flake8'
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
Build step 'Execute shell' marked build as failure
Setting status of 07f0c26c68476dba94df8d83ca3eb9d27c8f540a to FAILURE with url http://bock.systems:8080/job/hangups_tox/27/ and message: Merged build finished.
```

Oh No...

**Comment by PHLAK** [comment]
I still want to impliment a check when linking to comics out of the date range of valid comics.

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/28/
Tests Passed, Yay.

**Comment by Penguin2600** [comment]
:horse:

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/29/

**Build Log**
_last 25 lines_

```
[...truncated 5 lines...]
 > git config remote.origin.url https://github.com/TheInnerCircleO/hangupsbot # timeout=10
Fetching upstream changes from https://github.com/TheInnerCircleO/hangupsbot
 > git --version # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/TheInnerCircleO/hangupsbot +refs/pull/*:refs/remotes/origin/pr/*
 > git rev-parse refs/remotes/origin/pr/17/merge^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/pr/17/merge^{commit} # timeout=10
Checking out Revision 9ded37ab14a64f3650827a81cf2dba26cf9f1336 (refs/remotes/origin/pr/17/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 9ded37ab14a64f3650827a81cf2dba26cf9f1336
First time build. Skipping changelog.
[workspace] $ /bin/bash /tmp/hudson1641616111718324565.sh
pep8 recreate: /var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8
pep8 installdeps: -r/var/lib/jenkins/jobs/hangups_tox/workspace/requirements.txt, -r/var/lib/jenkins/jobs/hangups_tox/workspace/test-requirements.txt
pep8 develop-inst: /var/lib/jenkins/jobs/hangups_tox/workspace
pep8 runtests: PYTHONHASHSEED='1991810491'
pep8 runtests: commands[0] | flake8
./hangupsbot/commands.py:7:1: F401 'time' imported but unused
import time
^
ERROR: InvocationError: '/var/lib/jenkins/jobs/hangups_tox/workspace/.tox/pep8/bin/flake8'
___________________________________ summary ____________________________________
ERROR:   pep8: commands failed
Build step 'Execute shell' marked build as failure
Setting status of e93a65c54f227d0cd95f2147dd961ee4ec57f8f8 to FAILURE with url http://bock.systems:8080/job/hangups_tox/29/ and message: Merged build finished.
```

Oh No...

**Comment by System-Flenser** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://bock.systems:8080/job/hangups_tox/30/
Tests Passed, Yay.

**Comment by PHLAK** [comment]
Ready for merge when approved.

**Comment by uberscientist** [comment]
Nice :m: :e-mail: :m: :e-mail:

**Comment by PHLAK** [comment]
@Penguin2600 @Eamnon Any final comments before we merge this?

**Comment by Penguin2600** [comment]
Up to david, you are messing with his bb this time.

**Comment by DavidCaudill** [comment]
ill just improve it later

**Comment by DavidCaudill** [comment]
watchmen-20090223034904160

**Comment by uberscientist** [comment]
I press the button

**Pull request merged**
